### ISSUE TITLE
Pushbutton LED tutorial

### ISSUE THREAD

**Issue by seveibar** [tscircuit/docs-old#24]
https://snippets.tscircuit.com/editor?snippet_id=b210fe24-41d6-4465-b6a5-e99658e1dffa

**Comment by ShiboSoftwareDev** [comment]
/attempt #24

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/ShiboSoftwareDev) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @ShiboSoftwareDev | 5 tscircuit bounties | <div align="center">TypeScript, JavaScript, <br />HTML</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm3647qox0008l703vjelzcvc/cancel-attempt) |
