### ISSUE TITLE
Create a tutorial that demonstrates how to create an OR gate using TTL logic chips

### ISSUE THREAD

**Issue by seveibar** [tscircuit/docs-old#35]
Same criteria as #34, the hardest part is creating the snippet. The markdown doc is easy after

- There are 2 push buttons
- There are 4 LEDs
- There's a USBC connector for power
- There's an OR logic chip (that is popular and in-stock, probably from texas instruments)
- When BUTTON1 is pressed, LED1 turns on
- When BUTTON2 is pressed, LED2 turns on
- When BUTTON1 or BUTTON2 is pressed, LED3 turns on because of the OR gate
- When there is power (USBC is connected) LED4 turns on
- The schematic is readable (not everything clumped)
- The PCB has no errors

See [USBC Flashlight](https://snippets.tscircuit.com/editor?snippet_id=b210fe24-41d6-4465-b6a5-e99658e1dffa)

@ShiboSoftwareDev curious if you'd be interested in an issue like this

/bounty $50

**Comment by ShiboSoftwareDev** [comment]
@seveibar If I understand correctly you want something like bun guides, create a snippet and then instructions of how to create and use it

**Comment by seveibar** [comment]
Yep!!!

**Comment by ShiboSoftwareDev** [comment]
/attempt #35

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/ShiboSoftwareDev) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @ShiboSoftwareDev | 6 tscircuit bounties | <div align="center">TypeScript, JavaScript, <br />HTML</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm365pnvn0004jr038vm53rup/cancel-attempt) |

**Comment by Abse2001** [comment]
/attempt #35

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/Abse2001) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @Abse2001 | 1 tscircuit bounty | <div align="center">TypeScript</div> | <div align="center">﹟314</div> | [Cancel attempt](https://console.algora.io/api/bounties/cm365pnvn0004jr038vm53rup/cancel-attempt) |
